# I know you wondering why i named it numbp guesso, me too mate, me too.
# This is a number guessing game where the player must guess the number randomly generated by the game.
import random


def random_number():        # To generate the random number.
    min_value = 1
    max_value = 100
    random_number = random.randint(min_value, max_value)
    return random_number

target_number = random_number()     # To save the value of the generated random number.

while True:                         # To ensure the game continues asking for input until they guess the correct answer.
    guessed_number = int(input("Guess number: "))

    if guessed_number > target_number:
        print("The guessed number is greater than the random number!")
        print(guessed_number)
    elif guessed_number < target_number:
        print("The guessed number is lower than the random number!")
        print(guessed_number)
    elif guessed_number == target_number:
        print("Congratulation, You've got the number right!!")
        break                                                                                   # They guess the target number correctly, ending the loop.
    else:
        print("Invalid Input!")